# permissions for end users to view syncsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sync-credential-operator
    app.kubernetes.io/managed-by: kustomize
  name: syncsecret-viewer-role
rules:
- apiGroups:
  - sync.abroadme.me
  resources:
  - syncsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sync.abroadme.me
  resources:
  - syncsecrets/status
  verbs:
  - get
